apiVersion: v1
kind: Service
metadata:
  name: mediawiki
spec:
  type: LoadBalancer
  selector:
    app: mediawiki
    env: {{ .Values.env }}
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80