name: Change Prod Environment

on:
  workflow_dispatch:
    inputs:
        liveEnvironment:
            default: green
            required: true
            type: choice
            options:
            - blue
            - green

jobs:

  deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
      with:
        ref: main
        
    - name: 'Az CLI login'
      uses: azure/login@v1
      with:
        client-id: ${{ secrets.AZURE_CLIENT_ID }}
        tenant-id: ${{ secrets.AZURE_TENANT_ID }}
        subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    - name: Set AKS Context
      run: |
        az aks get-credentials --resource-group 'tw-mw-rg' --name 'tw-mw-cluster'

    - name: Update Deployment
      run: |
        cd ./helm/
        helm upgrade --set env=${{ inputs.liveEnvironment }} service ./service/
        kubectl describe svc mediawiki